### ISSUE TITLE
NoMethodError: undefined method `call' for RLetters::Analysis::Frequency:Module

### ISSUE THREAD

**Issue by cpence** [rletters/rletters#100]
It would seem that the Network code, when loaded from the job worker, isn't correctly seeing the Frequency analyzer. Serious issue, fixing now.

https://sentry.io/evotext/evotext/issues/581650338/

```
NoMethodError: undefined method `call' for RLetters::Analysis::Frequency:Module
  lib/r_letters/analysis/network/graph.rb:145:in `add_nodes_for_gap'
    analyzer = Frequency.call(
  lib/r_letters/analysis/network/graph.rb:77:in `block in initialize'
    add_nodes_for_gap(g)
  lib/r_letters/analysis/network/graph.rb:76:in `each'
    gaps.each_with_index do |g, i|
  lib/r_letters/analysis/network/graph.rb:76:in `each_with_index'
    gaps.each_with_index do |g, i|
  lib/r_letters/analysis/network/graph.rb:76:in `initialize'
    gaps.each_with_index do |g, i|
...
(93 additional frame(s) were not displayed)

NoMethodError: undefined method `call' for RLetters::Analysis::Frequency:Module
```

**Comment by cpence** [comment]
07a1edb is an attempted fix for this issue. We'll see whether or not we get another report of this in production. Keeping the bug open for the moment.

**Comment by cpence** [comment]
I think this has been resolved by a combination of the above commit and the new Zeitwerk autoloading framework present in Rails 6. At least, I haven't seen this bug reproduce in quite some time.
