### ISSUE TITLE
ArgumentError: comparison of NilClass with String failed

### ISSUE THREAD

**Issue by cpence** [rletters/rletters#108]
https://sentry.io/organizations/evotext/issues/1135071235/?referrer=github_plugin

```
ArgumentError: comparison of NilClass with String failed
  lib/r_letters/analysis/count_articles_by_field.rb:179:in `each'
    range = (counts.keys + normalization_counts.keys).minmax
  lib/r_letters/analysis/count_articles_by_field.rb:179:in `minmax'
    range = (counts.keys + normalization_counts.keys).minmax
  lib/r_letters/analysis/count_articles_by_field.rb:179:in `zero_intervening'
    range = (counts.keys + normalization_counts.keys).minmax
  lib/r_letters/analysis/count_articles_by_field.rb:201:in `normalize_counts'
    return zero_intervening(counts) unless normalize
  lib/r_letters/analysis/count_articles_by_field.rb:41:in `call'
    counts: normalize_counts(dataset ? group_dataset : group_corpus),
...
(100 additional frame(s) were not displayed)

ArgumentError: comparison of NilClass with String failed
```

**Comment by cpence** [comment]
Fixed in fe52bdc.
