### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by cpence** [rletters/rletters#109]
https://sentry.io/organizations/evotext/issues/1135074129/?referrer=github_plugin

```
NoMethodError: undefined method `split' for nil:NilClass
  lib/r_letters/analysis/count_articles_by_field.rb:141:in `get_field_from_document'
    parts = doc.year.split(%r{[-/]})
  lib/r_letters/analysis/count_articles_by_field.rb:58:in `block in group_dataset'
    key = get_field_from_document(doc)
  lib/r_letters/datasets/document_enumerator.rb:65:in `block (2 levels) in each'
    search_result.documents.each { |doc| yield(doc) }
  lib/r_letters/datasets/document_enumerator.rb:65:in `each'
    search_result.documents.each { |doc| yield(doc) }
  lib/r_letters/datasets/document_enumerator.rb:65:in `block in each'
    search_result.documents.each { |doc| yield(doc) }
...
(103 additional frame(s) were not displayed)

NoMethodError: undefined method `split' for nil:NilClass
```

**Comment by cpence** [comment]
Fixed in fe52bdc.
